// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZgVyrcqLs2ERgJe4lgJAI46TCQ4fLO1I',
    appId: '1:107177628860:web:93a5e9c41db1fffca86cb9',
    messagingSenderId: '107177628860',
    projectId: 'do-some-17de4',
    authDomain: 'do-some-17de4.firebaseapp.com',
    storageBucket: 'do-some-17de4.appspot.com',
    measurementId: 'G-F393D3CZ05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANyeEivXjb0ihPt2a7iN47rwl9TlmFzOs',
    appId: '1:107177628860:android:ca8420eceda44260a86cb9',
    messagingSenderId: '107177628860',
    projectId: 'do-some-17de4',
    storageBucket: 'do-some-17de4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7u7iFzgPfRU9CtSd_PPRN1o4EXJaFSJg',
    appId: '1:107177628860:ios:94bfc23251a61fbaa86cb9',
    messagingSenderId: '107177628860',
    projectId: 'do-some-17de4',
    storageBucket: 'do-some-17de4.appspot.com',
    iosBundleId: 'com.example.doSome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7u7iFzgPfRU9CtSd_PPRN1o4EXJaFSJg',
    appId: '1:107177628860:ios:94bfc23251a61fbaa86cb9',
    messagingSenderId: '107177628860',
    projectId: 'do-some-17de4',
    storageBucket: 'do-some-17de4.appspot.com',
    iosBundleId: 'com.example.doSome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZgVyrcqLs2ERgJe4lgJAI46TCQ4fLO1I',
    appId: '1:107177628860:web:dffbd5777148c509a86cb9',
    messagingSenderId: '107177628860',
    projectId: 'do-some-17de4',
    authDomain: 'do-some-17de4.firebaseapp.com',
    storageBucket: 'do-some-17de4.appspot.com',
    measurementId: 'G-784YVJH23M',
  );

}